version: '3.1'
services:
  springboot:
    build: .
    restart: always
    container_name: bootdockercontainer
    ports:
      - 9090:9090
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongodb_image
    container_name: mongodbcontainer
    ports:
      - 27017:27017
    restart: always

